---
- name: Testing andrewrothstein.summon
  hosts: all
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - name: Executing 'summon --version'
      ansible.builtin.command: summon --version
      changed_when: false
      register: summon_test_output
    - name: Output from 'summon --version'
      ansible.builtin.debug:
        msg: '{{ summon_test_output.stdout }}'
