---
- hosts: all
  roles:
  - role: '{{ playbook_dir }}'
  tasks:
  - command: /usr/local/bin/summon --version
    register: summon_test_output
  - name: summon --version
    debug:
      msg: '{{ summon_test_output.stdout }}'
