---
- include_role:
    name: andrewrothstein.unarchive-deps
- name: resolve platform specific vars
  include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/vars'
- name: checking for install in {{ summon_install_dir }}
  become: true
  stat:
    path: '{{ summon_install_dir }}'
  changed_when: false
  register: summon_binary
- when: not summon_binary.stat.exists
  block:
    - name: downloading {{ summon_url }}
      become: true
      become_user: root
      get_url:
        url: '{{ summon_url }}'
        dest: '{{ summon_tmp_archive }}'
        checksum: '{{ summon_checksum }}'
        mode: 0644
    - name: mkdir {{ summon_install_dir }}
      become: true
      become_user: root
      file:
        path: '{{ summon_install_dir }}'
        state: directory
        mode: 0755
    - name: unarchiving {{ summon_tmp_archive }}
      become: true
      become_user: root
      unarchive:
        remote_src: true
        src: '{{ summon_tmp_archive }}'
        dest: '{{ summon_install_dir }}'
        creates: '{{ summon_install_dir }}/summon'
  always:
    - name: rm {{ summon_tmp_archive }}
      become: true
      become_user: root
      file:
        path: '{{ summon_tmp_archive }}'
        state: absent
- name: linking {{ summon_link }} to {{ summon_exe }}
  become: true
  become_user: root
  file:
    src: '{{ summon_exe }}'
    dest: '{{ summon_link }}'
    state: link
